dryRun: true
tagFormat: "${version}"
branches:
    - "+([0-9])?(.{+([0-9]),x}).x"
    - { name: "master", prerelease: false }
    - { name: "next", prerelease: true, channel: "next" }
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - - "@semantic-release/exec"
      - generateNotesCmd: printf %s ${btoa(nextRelease.version)} | base64 -d > VERSION
    - - "@semantic-release/exec"
      - generateNotesCmd: printf %s ${btoa(nextRelease.notes)} | base64 -d > CHANGELOG
