tagFormat: "${version}"
branches:
    - "+([0-9])?(.{+([0-9]),x}).x"
    - { name: "main", prerelease: false }
    - { name: "next", prerelease: true, channel: "next" }
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - - "@semantic-release/changelog"
      - changelogFile: version/CHANGELOG
    - - "@semantic-release/exec"
      - publishCmd: cat "${nextRelease.version}" > version/VERSION
