name: CI/CD

on:
    push:
        branches:
            - "+([0-9])?(.{+([0-9]),x}).x"
            - master
            - next
    pull_request:
        branches:
            - "+([0-9])?(.{+([0-9]),x}).x"
            - next

jobs:
    version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: version/
                  key: version_${{ github.sha }}

            - run: npm i -g semantic-release @semantic-release/changelog
            - run: cp .github/.releaserc.yml .
            - run: npx semantic-release

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: .terraform/
                  key: ${{ hashFiles('.terraform.lock.hcl') }}
            - uses: actions/cache@v2
              with:
                  path: dist/
                  key: build_${{ github.sha }}
            - uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: "1.1.4"

            - run: terraform init
            - run: terraform fmt -check
            - run: terraform validate -no-color

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: .terraform/
                  key: ${{ hashFiles('.terraform.lock.hcl') }}
            - uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: "1.1.4"

            - run: echo test

    release:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: version/
                  key: version_${{ github.sha }}
            - uses: actions/cache@v2
              with:
                  path: dist/
                  key: build_${{ github.sha }}

            - run: git tag $(cat version/VERSION) && git push --tag
            - uses: softprops/action-gh-release@v1
              with:
                  body_path: version/CHANGELOG
                  files: dist/**
